services:
  mysql:
    image: mysql:8.0
    container_name: dev
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - share_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  share_data:
